FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN python -c "import nltk; nltk.download('omw-1.4'); nltk.download('wordnet')"

COPY . ./app

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]